import { createElement } from 'lwc';
import Client_Score_Report_dashboard from 'c/client_Score_Report_dashboard';

describe('c-client-score-report-dashboard', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-client-score-report-dashboard', {
            is: Client_Score_Report_dashboard
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});