name: Conditional Scan

on:
  push:
    branches:
      - feature_2

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: get-changes
        run: |
          git fetch --unshallow || true
          if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
            echo "Fetching changed files between HEAD~1 and HEAD"
            git diff --name-only HEAD~1 HEAD > changed_files.txt
          else
            echo "No previous commit to compare to." > changed_files.txt
          fi
          cat changed_files.txt

      - name: Determine if delta changes exist
        id: check-delta
        run: |
          files=$(cat changed_files.txt | grep -E '\.cls$|\.lwc$' || true)
          if [ -n "$files" ]; then
            echo "delta=true" > delta.txt
          else
            echo "delta=false" > delta.txt
          fi

      - name: Upload delta result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: delta-result
          path: delta.txt
