name: Conditional Scan

#condition
on:
  push:
    branches:
      - feature_2

jobs:
  check-delta:
    runs-on: ubuntu-latest
    outputs:
      delta: ${{ steps.check.outputs.delta }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: git fetch --unshallow || true

      - name: Check for Delta Changes
        id: check
        run: |
          git diff --name-only HEAD~1 HEAD > changed_files.txt
          if grep -E '\.cls$|\.lwc$' changed_files.txt; then
            echo "::set-output name=delta::true"
          else
            echo "::set-output name=delta::false"
          fi

  trigger-workflow:
    needs: check-delta
    if: ${{ needs.check-delta.outputs.delta == 'true' }}
    uses: ./.github/workflows/delta-scan.yml
    with:
      ref: ${{ github.ref }}

  trigger-workflow-overall:
    needs: check-delta
    if: ${{ needs.check-delta.outputs.delta == 'false' }}
    uses: ./.github/workflows/scan-code.yml
    with:
      ref: ${{ github.ref }}
