name: Delta Report

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: get-changes
        run: |
          git fetch origin
          BASE_COMMIT=$(git rev-parse HEAD^)
          git diff --name-only $BASE_COMMIT HEAD > changed_files.txt || true
          cat changed_files.txt
      

      - name: Generate report
        id: generate_report
        run: |
          # Create a report based on changed files
          echo "## Delta Report" > delta_report.md
          echo "The following files were changed in this commit:" >> delta_report.md
          cat changed_files.txt >> delta_report.md

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: delta-report
          path: delta_report.md
