name: Vulnerability Report

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor
      - "**"

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x  # Use the appropriate Node.js version for your project

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        id: get-changes
        run: |
          git fetch --unshallow || true
          if [ "$(git rev-list --count HEAD)" -gt "1" ]; then
            git diff --name-only HEAD~1 HEAD > changed_files.txt
          else
            echo "No previous commit to compare to." > changed_files.txt
          fi
          cat changed_files.txt

      - name: Create a list of files to audit
        id: prepare_audit_list
        run: |
          # Ensure files_to_audit.txt is created, even if no matches are found
          grep 'package.json$' changed_files.txt > files_to_audit.txt || true
          if [ ! -s files_to_audit.txt ]; then
            echo "No package.json files changed." > files_to_audit.txt
          fi
          cat files_to_audit.txt

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk and generate report
        id: run_snyk
        run: |
          mkdir -p reports
          snyk test --json > reports/snyk_report.json
          # Convert JSON report to CSV (using a custom script or tool)
          npx json2csv -i reports/snyk_report.json -o reports/snyk_report.csv || true
          cat reports/snyk_report.csv

      - name: Upload CSV report
        uses: actions/upload-artifact@v3
        with:
          name: vulnerability-report
          path: reports/snyk_report.csv
