name: SFDX Code Scan Overall

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  installcli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install CLI
        run: npm install @salesforce/cli --global
      - name: Install Scanner Plugin
        run: sf plugins install @salesforce/sfdx-scanner
      - name: Verify SFDX CLI Installation
        run: sf --version
      - name: Verify SFDX Scanner Plugin Installation
        run: sf plugins --core
      - name: Run SFDX Scanner
        run: |
          sf scanner:run --target "force-app/main/default/classes/**/*.cls,force-app/main/default/lwc" --format "csv" --outfile "scanner-report.csv"
        env:
          SF_LAZY_LOAD_MODULES: 'true'
          SF_AUTOUPDATE_DISABLE: 'true'
          SF_DISABLE_AUTOUPDATE: 'true'
      - name: Upload CSV Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scanner-report
          path: scanner-report.csv
