name: SFDX Code Scan

on:
  push:
    branches:
      - main
      - '**'

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
      - name: Install SFDX Scanner Plugin
        run: |
          sfdx plugins:install @salesforce/sfdx-scanner
      - name: Verify SFDX CLI Installation
        run: |
          sfdx --version
      - name: Verify SFDX Scanner Plugin Installation
        run: |
          sfdx plugins --core
      - name: Run SFDX Scanner
        run: |
          sfdx scanner:run --target "force-app/main/default/classes,force-app/main/default/lwc" --format "csv" --outfile "scanner-report.csv"
        env:
          SF_LAZY_LOAD_MODULES: 'true'
          SF_AUTOUPDATE_DISABLE: 'true'
          SF_DISABLE_AUTOUPDATE: 'true'
      - name: Encode CSV file to Base64
        id: encode_file
        run: |
          base64 scanner-report.csv | tr -d '\n' > encoded_report.txt
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Upload CSV Report to Salesforce
        run: |
          contentDocumentResponse=$(curl -X POST https://sprintparksolutionspvtltd-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/ \
            -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "Title": "Scanner Report",
              "PathOnClient": "scanner-report.csv",
              "VersionData": "'"$(cat encoded_report.txt)"'"
            }')
          echo "Response: $contentDocumentResponse"
          
          contentVersionId=$(echo $contentDocumentResponse | jq -r '.id // empty')
          if [ -z "$contentVersionId" ]; then
            echo "Error: Failed to upload file. No ContentVersionId found."
            exit 1
          fi
          echo "ContentVersionId: $contentVersionId"
          
          contentDocumentResponse=$(curl -X GET https://sprintparksolutionspvtltd-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/ContentVersion/$contentVersionId \
            -H "Authorization: Bearer ${{ secrets.SF_ACCESS_TOKEN }}")
          echo "ContentDocument Response: $contentDocumentResponse"
          
          contentDocumentId=$(echo $contentDocumentResponse | jq -r '.ContentDocumentId // empty')
          if [ -z "$contentDocumentId" ]; then
            echo "Error: Failed to retrieve ContentDocumentId. No ContentDocumentId found."
            exit 1
          fi
          echo "ContentDocumentId: $contentDocumentId"
        env:
          SF_ACCESS_TOKEN: ${{ secrets.SF_ACCESS_TOKEN }}
        shell: bash
